name: Build Server

on:
  workflow_dispatch: 

env:
  QT_VERSION: '6.2.4'

jobs:
  build:
    runs-on: linux
    container:
      image: git.odizinne.com/odizinne/noqt-ubuntu-22.04:latest

    steps:
      - uses: https://git.odizinne.com/Odizinne/gitea-actions/clone@main

      - name: Install Qt
        uses: https://git.odizinne.com/Odizinne/gitea-actions/install-qt@main
        with:
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
    
      - name: Configure (server only)
        run: |
          mkdir build-server
          cd build-server
          cmake ../server -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build-server --parallel

      - name: Upload server binary
        uses: https://git.odizinne.com/Odizinne/gitea-actions/upload-artifact@main
        with:
          name: GTACOMPTAServer
          path: build-server/GTACOMPTAServer
