name: Build Server

on:
  workflow_dispatch: 

env:
  QT_VERSION: '6.2.4'

jobs:
  build:
    runs-on: linux
    container:
      image: git.odizinne.com/odizinne/noqt-ubuntu-22.04:latest

    steps:
      - name: Clone repository
        run: |
          git clone --depth=1 https://git.odizinne.com/${{ gitea.repository }}.git .

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'

      - name: Configure (server only)
        run: |
          mkdir build-server
          cd build-server
          cmake ../server -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build-server --parallel

      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: GTACOMPTAServer
          path: build-server/GTACOMPTAServer
