name: Build Server

on:
  workflow_dispatch: 

env:
  QT_VERSION: '6.2.4'

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/odizinne/6.2.4-ubuntu-22.04:latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Configure (server only)
        run: |
          mkdir build-server
          cd build-server
          cmake ../server -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build-server --parallel

      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: GTACOMPTAServer
          path: build-server/GTACOMPTAServer
